In [1]:
import numpy as np

arr = np.ones((2, 3))  # Creates a 2x3 array filled with ones
arr2 = np.zeros((3, 3))  # Creates a 3x3 array filled with zeros
arr3 = np.full((2, 5), 7)  # Correctly creates a 2x5 array filled with the number 7


In [2]:
import numpy as np
arr = np.arange(4) 
arr_reshaped = arr.reshape(2, 2)
print(arr_reshaped**3)
print(arr_reshaped+7)
print(arr_reshaped*2)

[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [3]:
arr1=np.arange(2,19,2).reshape(3,3)
arr2=np.arange(9,0,-1).reshape(3,3)
arr1*arr2

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [4]:
import numpy as np

twoarr = np.array([[1, 2], [3, 4]])
twoarr[[0, 1]] = twoarr[[1, 0]]
twoarr[:, [0, 1]] = twoarr[:, [1, 0]]
print(twoarr)


[[4 3]
 [2 1]]


In [5]:
list1=[2,3,5,7,11]
list2=[13,17,19,23,29]
npa=np.array([list1,list2])
print(npa)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [6]:
npa=np.array([2**x for x in range(0,6,1)]).reshape(2,3)
print(npa.flatten())
print(npa.ravel())
print(npa)

[ 1  2  4  8 16 32]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]


In [7]:
from statistics import mode,mean
numbers = [6, 9, 5, 1, 7, 5, 1, 0, 1, 5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6]
npa=np.array(numbers)
print(mode(npa))

5


In [8]:
npa = np.linspace(1.1, 6.6, num=6).reshape(2, 3)
npa_int = npa.astype(int)
print(npa_int)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
def format_2darray(arr):
    max_val = 0
    for i in arr:
        for j in i:
            if j > max_val:
                max_val = j
    count = 0
    while max_val > 0:
        max_val //= 10
        count += 1
    for i in arr:
        for j in i:
            print(f"{j:>{count}}", end=' ') 
        print()
num = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 100]])
format_2darray(num)


  1   2   3   4   5 
  6   7   8   9 100 


In [10]:
num=np.arange(1,16,1).reshape(3,5)
print(num)
print(num[1])
print(num[:,4])
print(num[0:2])
print(num[1,4])
print(num[1:3,[0,2,4]])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 6  7  8  9 10]
[ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
[[ 6  8 10]
 [11 13 15]]


In [12]:
array1=np.array([[0,1],[2,3]])
array2=np.array([[4,5],[6,7]])
array3=np.vstack((array1,array2))
array4=np.hstack((array1,array2))
print(array3)
print(array4)
array5=np.vstack((array4,array4))
print(array5)
array6=np.hstack((array3,array3))
print(array6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
