In [1]:
import numpy as np

arr = np.ones((2, 3))  # Creates a 2x3 array filled with ones
arr2 = np.zeros((3, 3))  # Creates a 3x3 array filled with zeros
arr3 = np.full((2, 5), 7)  # Correctly creates a 2x5 array filled with the number 7


In [2]:
import numpy as np
arr = np.arange(4) 
arr_reshaped = arr.reshape(2, 2)
print(arr_reshaped**3)
print(arr_reshaped+7)
print(arr_reshaped*2)

[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [3]:
arr1=np.arange(2,19,2).reshape(3,3)
arr2=np.arange(9,0,-1).reshape(3,3)
arr1*arr2

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [4]:
import numpy as np

twoarr = np.array([[1, 2], [3, 4]])
twoarr[[0, 1]] = twoarr[[1, 0]]
twoarr[:, [0, 1]] = twoarr[:, [1, 0]]
print(twoarr)


[[4 3]
 [2 1]]


In [5]:
list1=[2,3,5,7,11]
list2=[13,17,19,23,29]
npa=np.array([list1,list2])
print(npa)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [6]:
npa=np.array([2**x for x in range(0,6,1)]).reshape(2,3)
print(npa.flatten())
print(npa.ravel())
print(npa)

[ 1  2  4  8 16 32]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]


In [7]:
from statistics import mode,mean
numbers = [6, 9, 5, 1, 7, 5, 1, 0, 1, 5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6]
npa=np.array(numbers)
print(mode(npa))

5


In [8]:
npa = np.linspace(1.1, 6.6, num=6).reshape(2, 3)
npa_int = npa.astype(int)
print(npa_int)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
def format_2darray(arr):
    max_val = 0
    for i in arr:
        for j in i:
            if j > max_val:
                max_val = j
    count = 0
    while max_val > 0:
        max_val //= 10
        count += 1
    for i in arr:
        for j in i:
            print(f"{j:>{count}}", end=' ') 
        print()
num = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 100]])
format_2darray(num)


  1   2   3   4   5 
  6   7   8   9 100 


In [10]:
num=np.arange(1,16,1).reshape(3,5)
print(num)
print(num[1])
print(num[:,4])
print(num[0:2])
print(num[1,4])
print(num[1:3,[0,2,4]])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 6  7  8  9 10]
[ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
[[ 6  8 10]
 [11 13 15]]


In [11]:
array1=np.array([[0,1],[2,3]])
array2=np.array([[4,5],[6,7]])
array3=np.vstack((array1,array2))
array4=np.hstack((array1,array2))
print(array3)
print(array4)
array5=np.vstack((array4,array4))
print(array5)
array6=np.hstack((array3,array3))
print(array6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [12]:
array1=np.array([[0,1],[2,3]])
array2=np.array([[4,5],[6,7]])
array3=np.concatenate((array1,array2),axis=0)
array4=np.concatenate((array1,array2),axis=1)
array5=np.concatenate((array4,array4),axis=0)
array6=np.concatenate((array1,array2),axis=1)
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [13]:
import numpy as np
pattern = np.array([['-', '*'], 
                         ['*', '-']])


checkerboard = np.tile(pattern, (4, 4)) 

checkerboard


array([['-', '*', '-', '*', '-', '*', '-', '*'],
       ['*', '-', '*', '-', '*', '-', '*', '-'],
       ['-', '*', '-', '*', '-', '*', '-', '*'],
       ['*', '-', '*', '-', '*', '-', '*', '-'],
       ['-', '*', '-', '*', '-', '*', '-', '*'],
       ['*', '-', '*', '-', '*', '-', '*', '-'],
       ['-', '*', '-', '*', '-', '*', '-', '*'],
       ['*', '-', '*', '-', '*', '-', '*', '-']], dtype='<U1')

In [14]:
random_array = np.random.randint(0, 100, size=(5, 5))
print(random_array)
np.bincount(random_array.flatten())

[[43 83 28 32 65]
 [ 4 81 41  7 25]
 [32 77 27 81 33]
 [29 46 67 41 79]
 [70 38 92 61 85]]


array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1], dtype=int64)

In [15]:
import numpy as np

def median(arr):
    return np.median(arr)

def mode(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    return values[max_count_index]

arr1 = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print(f"Array 1 (1D): {arr1}")
print(f"Median: {median(arr1)}")
print(f"Mode: {mode(arr1)}")

arr2 = np.array([[1, 2, 2], [3, 4, 4], [4, 5, 6]])
print(f"\nArray 2 (2D):\n{arr2}")
print(f"Median: {median(arr2)}")
print(f"Mode: {mode(arr2)}")

arr3 = np.random.randint(1, 10, (3, 3, 3))
print(f"\nArray 3 (3D):\n{arr3}")
print(f"Median: {median(arr3)}")
print(f"Mode: {mode(arr3)}")


Array 1 (1D): [1 2 2 3 4 4 4 5]
Median: 3.5
Mode: 4

Array 2 (2D):
[[1 2 2]
 [3 4 4]
 [4 5 6]]
Median: 4.0
Mode: 4

Array 3 (3D):
[[[9 6 5]
  [9 8 2]
  [2 1 5]]

 [[3 1 3]
  [6 5 4]
  [1 6 2]]

 [[3 7 5]
  [8 2 7]
  [7 5 3]]]
Median: 5.0
Mode: 5


In [16]:
import numpy as np

arr = np.random.random((9, 9, 2))
print("Original array (9x9x2):\n", arr)

arr2 = arr[2:7, 2:7, :]
print("\nExtracted subarray (5x5x2):\n", arr2)

Original array (9x9x2):
 [[[0.13004903 0.91070233]
  [0.38253366 0.08174076]
  [0.80976083 0.6446278 ]
  [0.37435589 0.02531535]
  [0.77468852 0.21837172]
  [0.12223364 0.85828597]
  [0.73848835 0.4829873 ]
  [0.70282277 0.64868359]
  [0.45912647 0.93487111]]

 [[0.26571015 0.73347833]
  [0.80201593 0.12566438]
  [0.66378457 0.76011632]
  [0.54998078 0.32544916]
  [0.47795433 0.63457281]
  [0.94751125 0.29282086]
  [0.62421242 0.86824419]
  [0.08426525 0.12356   ]
  [0.01110547 0.9976676 ]]

 [[0.54659109 0.12994111]
  [0.71411646 0.1373469 ]
  [0.30368864 0.32813955]
  [0.7648872  0.98192961]
  [0.02156887 0.95517345]
  [0.59992106 0.31771202]
  [0.12786599 0.52382413]
  [0.40310485 0.57902729]
  [0.69279661 0.25903112]]

 [[0.08750376 0.3626362 ]
  [0.64186037 0.26385505]
  [0.86465944 0.39040473]
  [0.51808675 0.97572963]
  [0.75534127 0.19706952]
  [0.79306145 0.62193347]
  [0.14301834 0.68068609]
  [0.78856523 0.17763919]
  [0.59150043 0.61126687]]

 [[0.42700047 0.23732461]
  [0.

In [17]:
arr=np.random.random((4,4))
print(arr)
arr.sort(axis=0)
print(arr)

[[0.41133622 0.74681923 0.96047561 0.36054265]
 [0.85198813 0.7774197  0.00522787 0.03516748]
 [0.59024962 0.75103579 0.86802627 0.99886401]
 [0.44657752 0.13073875 0.69334018 0.44743635]]
[[0.41133622 0.13073875 0.00522787 0.03516748]
 [0.44657752 0.74681923 0.69334018 0.36054265]
 [0.59024962 0.75103579 0.86802627 0.44743635]
 [0.85198813 0.7774197  0.96047561 0.99886401]]
